[build]
  publish = "."

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[redirects]]
  from = "/404"
  to = "/404.html"
  status = 404

# Category depth-based rewrites
[[redirects]]
  from = "/c/:l1/:l2/:l3"
  to = "/category-level-3.html"
  status = 200

[[redirects]]
  from = "/c/:l1/:l2"
  to = "/category-level-2.html"
  status = 200

[[redirects]]
  from = "/c/:l1"
  to = "/category-level-1.html"
  status = 200

