#!/usr/bin/env sh

# husky
# get the absolute path to the directory of this script
dir="$(cd "$(dirname "$0")" && pwd)"

if [ -z "$husky_skip_init" ]; then
  debug () {
    [ "$HUSKY_DEBUG" = "1" ] && echo "husky (debug) - $1"
  }
  readonly hook_name="$(basename "$0")"
  debug "starting $hook_name..."
fi

